name: CI/CD for Final Project

on:
  push:
    branches:
      - main  # main 브랜치에 푸쉬될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@<EC2-PUBLIC-IP> << EOF
            cd /home/ec2-user/Final-Project
            git pull origin main
            docker-compose down -v
            docker-compose up -d --build
          EOF